### ISSUE TITLE
Add an option to have timers display in only one colour.

### ISSUE THREAD

**Issue by arcadepro** [xod-wow/LiteButtonAuras#3] opened 2021-09-15 21:34 UTC
Not a fan of the gradient colour timers myself so if you could add an option to not use it or set a fixed colour it would be cool.

**Comment by mbattersby** [comment] 2021-09-15 23:53
This is pretty straightforward, the issue is the 100 hours it will take to make a GUI for options. Perhaps I should just give up and use AceConfig or whatever the awful thing is called.

**Comment by mbattersby** [comment] 2021-09-16 01:26
9.1.4 adds a slash command and

`/lba colortimers on|off`

**Comment by arcadepro** [comment] 2021-09-16 01:47
I'm 100% fine with no gui :D hated adding them to my own addons. So I just stopped.

**Comment by mbattersby** [comment] 2021-09-16 03:58
\o/

Closing this for now, I'll add it to the GUI if there ever is one.

**Closed by mbattersby** 2021-09-16 03:58 UTC
