### ISSUE TITLE
Sometimes the Flash/pulse animation is getting getting stuck at the wrong scale for short periods.

### ISSUE THREAD

**Issue by arcadepro** [xod-wow/LiteButtonAuras#15] opened 2022-11-23 21:57 UTC
Not sure how to reliably reproduce this yet but Victory Rush (warrior base spell) is a good spell to observe.

While in combat the new flash overlay (new better texture version) gets seemingly stuck on screen, or rendered at the wrong scale for a short period. It's noticeable on Victory Rush (warrior). _This has only visibly happened, or looked like an obvious bug, since the updated texture change._

It's perhaps when you kill mobs in quick succession thus starting animation again before the previous loop has ended?

**Comment by mbattersby** [comment] 2022-11-23 22:52
As far as I know this is a Blizzard bug, see #13

LBA doesn't flash, pulse or resize anything.

**Comment by mbattersby** [comment] 2022-11-23 23:13
Can you check that you can reproduce it without LBA?

**Comment by arcadepro** [comment] 2022-11-24 03:30
Yeah, this seems to be the same issue as https://github.com/xod-wow/LiteButtonAuras/issues/13 
I'll try and find a way to repro.

**Comment by arcadepro** [comment] 2022-11-27 03:24
So I tried to trigger it (invasion spamming) using 10.0.7. No luck. Switched to 10.0.9. Triggered the bugged state about three times in 10mins.

![image](https://user-images.githubusercontent.com/1977760/204117799-0739a1e3-a8d5-4fc4-a440-2931ea7b05d8.png)

Could be anecdotal I guess. I'll keep trying on 10.0.7.

**Comment by mbattersby** [comment] 2022-11-27 11:26
Are you using any other addon that embeds LibButtonGlow?

What is red-ing out Shield Slam and charge in your screenshot?\

LBA does try to show Victorious on Victory Rush and Impending Victory, but only as a green highlight not as a "suggest this button" as shown. And it never touches the actual action button itself, all of LBA is a completely separate overlay positioned over the top of the button.

It looks like what's happening here is that the glow/suggest anim is getting stopped but not canceled and the "animOut" isn't shutting it down. But I have no idea whose glow/suggest anim it is since LBA shouldn't be trying to do one there.

**Comment by mbattersby** [comment] 2022-11-27 23:05
This person seems to be reporting the same problem with no addons:

https://www.reddit.com/r/WowUI/comments/z68i8p/button_proc_glow_bug_help/

**Comment by mbattersby** [comment] 2022-11-28 00:14
This is definitely a Blizzard bug, I can trigger it easily with no addons. I've logged with Blizzard in-game and here

https://github.com/Stanzilla/WoWUIBugs/issues/358

I'll leave this open in case anyone else comes to report it.

**Comment by arcadepro** [comment] 2022-11-28 02:44
The red-out is Tullarange. Your addon is the only one I have with LibButtonGlow in use.

**Comment by mbattersby** [comment] 2022-11-29 10:52
I tested this at great length and although it's not an LBA bug, somehow LBA makes it trigger **A LOT** more. Like 50 times more. I've fixed a minor bug that I think helps with this in 10.0.10 even if I'm not really sure why.

**Comment by mbattersby** [comment] 2023-06-23 07:11
I got sick of waiting for Blizzard to fix their bug, and put a workaround in a7dec1a / 10.1.0-5

Gonna close this off and leave the WoWUIBugs to handle it from the Blizzard end.

**Closed by mbattersby** 2023-06-23 07:11 UTC
